### ISSUE TITLE
Review BEL specifications for 1.0 and 2.0

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/bel_parser#32]
BEL specifications live in the [OpenBEL/language](https://github.com/OpenBEL/language) repository.

The rendered HTML is also committed to the repository. It is then published to http://openbel.github.io/language/version_2.0/bel_specification_version_2.0.html using GitHub pages.

- Review formatting
- Link to BEL Examples for 1.0 and 2.0 on OpenBEL wiki instead of enumerating examples.
- Link to BEL best practices for 1.0 and 2.0 on OpenBEL wiki instead of enumerating best practices.

FYI, If you need to copy over content from the wiki you can copy/paste into AsciiDoc format using the http://asciidocfx.com/ tool.

**Comment by wshayes** [comment]
https://github.com/OpenBEL/language

Should be main landing page for all BEL Language content linking to specification docs on github, examples on wiki, etc:  http://wiki.openbel.org/display/BEL/BEL+Language+Home

Terminology update (https://github.com/OpenBEL/openbel-platform  has link to Terminology page.  Should make sure there isn't a terminology/glossary page on Wiki and link to this one from wiki):
Evidence -> Summary Text -> Support
?? -> Evidence -> BEL Nanopub
KAM -> BKN (BEL Knowledge Network)
evidence : summary text TRANSFORMS_TO nanopub : support

https://github.com/OpenBEL/openbel.github.io  (repo for the http://openbel.github.io -- longer term this should tied together all dev aspects of OpenBEL content/tools/etc)
http://asciidoctor.org/docs/asciidoc-writers-guide

The gh-pages branch has the website pages for: http://openbel.github.io/language
http://openbel.github.io/language/version_2.0/bel_specification_version_2.0.html

https://github.com/OpenBEL/language/blob/master/version_2.0/bel_specification_version_2.0.adoc  (can be viewed in asciidoc format by clicking on Raw button in github repo (master branch)  otherwise by default you see the html formatted version which is automatically created by github when viewing md, rst, adoc (markdown, restructured text, asciidoc) files

BEL 2.0 Specification Wiki space
http://wiki.openbel.org/pages/viewpage.action?pageId=10387763

http://wiki.openbel.org/display/BEL/BEL+Language+Home   (should be main landing page for all BEL Language versions (the BEL1 and BEL2 appendices that are being kept on the wiki should be moved into this space and linked to from the specification and  http://openbel.github.io/language/ page) 
http://wiki.openbel.org/display/BLD/BEL+Examples       1.0 examples
http://wiki.openbel.org/display/BLVD/BEL+Examples      2.0 examples
